### PR TITLE
Include comments on ERA5 dataset download

### PR DESCRIPTION
**Pull request by euronion**
Thank you for updating to the CDS API for ERA5! @coroa 

Since you kind of beat me to it, I figured I'll at least provide the comments
I added to the code while coding my own version.

### CODE REVIEW

**Comment by coroa** [comment]
Thanks for the comments. I'd say I beat you proper and square to it :).

**Comment by nworbmot** [comment]
Hi both, I was also about to do the CDS change before I saw @coroa had done it (I had already spent 1 hour looking at the interface). Maybe next time we should communicate better to avoid triple work? :-)

**Comment by euronion** [comment]
> [...] Maybe next time we should communicate better to avoid triple work? :-)

Agreed! =)
Probably the easiest & most transparent way to go would be opening and (self-) assigning issues?

**Comment by coroa** [comment]
I think that's the best option, yes!

**Pull request merged**
